/* ═══════════════════════════════════════════════════
   SideQuest — data.js
   Centralised dummy data — replace with real API calls
═══════════════════════════════════════════════════ */

"use strict";

/* ── Lomba ── */
const lombaData = [
  {
    id: 1,
    cat: "teknologi",
    title: "Gemastik XVII — Pengembangan Perangkat Lunak",
    org: "Kemendikbud Ristek RI",
    deadline: "14 Mei 2026",
    daysLeft: 2,
    tags: ["Teknologi", "Nasional"],
    color: "from-primary to-purple-500",
    emoji: "🏆",
    free: true,
    prize: null,
    desc: "Kompetisi TIK mahasiswa nasional. Bidang PPL: web, mobile, desktop.",
  },
  {
    id: 2,
    cat: "bisnis",
    title: "ASEAN Business Plan Competition 2026",
    org: "ASEAN Youth Council",
    deadline: "21 Mei 2026",
    daysLeft: 9,
    tags: ["Bisnis", "ASEAN"],
    color: "from-orange-400 to-accent",
    emoji: "💼",
    free: false,
    prize: "Rp 500rb",
    desc: "Kompetisi rencana bisnis tingkat ASEAN untuk mahasiswa.",
  },
  {
    id: 3,
    cat: "sosial",
    title: "Hult Prize 2026 — Campus Round",
    org: "Hult International Business School",
    deadline: "3 Jun 2026",
    daysLeft: 22,
    tags: ["Social Impact", "Internasional"],
    color: "from-green-400 to-teal-500",
    emoji: "🌱",
    free: true,
    prize: null,
    desc: "Kompetisi startup sosial terbesar di dunia untuk mahasiswa.",
  },
  {
    id: 4,
    cat: "teknologi",
    title: "Hackathon Nasional 2026 — Smart City",
    org: "Kemenkominfo",
    deadline: "10 Jun 2026",
    daysLeft: 29,
    tags: ["Teknologi", "Hackathon"],
    color: "from-blue-500 to-primary",
    emoji: "🌆",
    free: true,
    prize: null,
    desc: "Hackathon 48 jam membangun solusi smart city inovatif.",
  },
  {
    id: 5,
    cat: "desain",
    title: "National UI/UX Design Challenge",
    org: "Tokopedia × Google DSC",
    deadline: "25 Jun 2026",
    daysLeft: 44,
    tags: ["Desain", "UI/UX"],
    color: "from-pink-400 to-purple-400",
    emoji: "🎨",
    free: true,
    prize: null,
    desc: "Desain pengalaman pengguna terbaik untuk platform e-commerce.",
  },
  {
    id: 6,
    cat: "sains",
    title: "Lomba Karya Tulis Ilmiah Nasional",
    org: "ITS Surabaya",
    deadline: "30 Jun 2026",
    daysLeft: 49,
    tags: ["Sains", "Ilmiah"],
    color: "from-cyan-500 to-blue-500",
    emoji: "🔬",
    free: false,
    prize: "Rp 200rb",
    desc: "LKTIN bidang teknologi, sains, dan inovasi untuk mahasiswa.",
  },
  {
    id: 7,
    cat: "teknologi",
    title: "Google Solution Challenge 2026",
    org: "Google Developer Student Clubs",
    deadline: "15 Jul 2026",
    daysLeft: 64,
    tags: ["Teknologi", "Global"],
    color: "from-red-400 to-orange-400",
    emoji: "⚡",
    free: true,
    prize: null,
    desc: "Bangun solusi untuk SDGs menggunakan teknologi Google.",
  },
  {
    id: 8,
    cat: "bisnis",
    title: "Startup Weekend Jakarta 2026",
    org: "Techstars × ANGIN",
    deadline: "20 Jul 2026",
    daysLeft: 69,
    tags: ["Bisnis", "Startup"],
    color: "from-yellow-400 to-orange-400",
    emoji: "🚀",
    free: false,
    prize: "Mentoring",
    desc: "54 jam dari ide ke pitch deck. Gabung komunitas startup terbaik.",
  },
];

/* ── Matchmaking candidates ── */
const matchData = [
  {
    id: 1,
    name: "Aurel Salsabila",
    uni: "ITB Bandung",
    prodi: "Sistem dan Teknologi Informasi",
    skills: ["UI/UX Design", "Figma", "User Research"],
    skillCats: ["ui-ux"],
    exp: ["Hult Prize 2025 — Juara 1", "COMPFEST Design Finalist"],
    prestasi: ["Ksatria Data", "Dokumentasi Terbaik"],
    compat: 90,
    online: true,
    avatarColor: "bg-purple-500",
  },
  {
    id: 2,
    name: "Bimo Prasetyo",
    uni: "ITS Surabaya",
    prodi: "Teknik Komputer",
    skills: ["Backend", "Node.js", "Database", "DevOps"],
    skillCats: ["backend"],
    exp: ["Gemastik XVI — Juara 2", "Hackathon Smart City 2025"],
    prestasi: ["Hackaton", "Ksatria Data"],
    compat: 85,
    online: true,
    avatarColor: "bg-blue-500",
  },
  {
    id: 3,
    name: "Citra Dewi",
    uni: "Universitas Gadjah Mada",
    prodi: "Manajemen",
    skills: ["Business Dev", "Pitching", "Market Research"],
    skillCats: ["business"],
    exp: ["ASEAN BPC 2025 — Finalist", "Startup Weekend 2024"],
    prestasi: ["Best Pitch", "Dokumentasi"],
    compat: 78,
    online: false,
    avatarColor: "bg-green-500",
  },
  {
    id: 4,
    name: "Dimas Arfian",
    uni: "BINUS University",
    prodi: "Computer Science",
    skills: ["Machine Learning", "Python", "Data Science"],
    skillCats: ["data-science"],
    exp: ["Kaggle Competition — Top 5%", "Data Olympiad 2025"],
    prestasi: ["Ksatria Data", "Kaggle Expert"],
    compat: 72,
    online: true,
    avatarColor: "bg-orange-500",
  },
  {
    id: 5,
    name: "Evan Wijaya",
    uni: "Universitas Indonesia",
    prodi: "Ilmu Komputer",
    skills: ["React.js", "Vue.js", "TypeScript", "CSS"],
    skillCats: ["frontend"],
    exp: ["Google DSC Lead 2025", "Web Dev Competition — Juara 1"],
    prestasi: ["Best Developer", "Google Badge"],
    compat: 88,
    online: true,
    avatarColor: "bg-cyan-500",
  },
  {
    id: 6,
    name: "Farah Nadia",
    uni: "Telkom University",
    prodi: "Desain Komunikasi Visual",
    skills: ["Figma", "Ilustrasi", "Branding", "UI/UX"],
    skillCats: ["ui-ux"],
    exp: ["Redot Design Award 2024", "COMPFEST Design — Juara 2"],
    prestasi: ["Best Design", "Creative Award"],
    compat: 82,
    online: false,
    avatarColor: "bg-pink-500",
  },
  {
    id: 7,
    name: "Galih Permana",
    uni: "Universitas Brawijaya",
    prodi: "Sistem Informasi",
    skills: ["Laravel", "PHP", "MySQL", "Backend"],
    skillCats: ["backend"],
    exp: ["Gemastik XVI — Peserta", "INAICTA 2024 Finalist"],
    prestasi: ["Inovator Muda"],
    compat: 69,
    online: true,
    avatarColor: "bg-indigo-500",
  },
  {
    id: 8,
    name: "Hana Kusuma",
    uni: "IPB University",
    prodi: "Statistika",
    skills: ["R Language", "Data Visualization", "Statistics", "Python"],
    skillCats: ["data-science"],
    exp: ["National Statistics Olympiad 2025 — Juara 3", "Data Analytics Bootcamp"],
    prestasi: ["Statistika Award", "Best Analysis"],
    compat: 75,
    online: false,
    avatarColor: "bg-teal-500",
  },
  {
    id: 9,
    name: "Ivan Santoso",
    uni: "BINUS University",
    prodi: "Mobile Application & Technology",
    skills: ["Flutter", "Dart", "React Native", "iOS/Android"],
    skillCats: ["frontend", "backend"],
    exp: ["Google Play Best App 2024", "Mobile Hackathon — Juara 1"],
    prestasi: ["Best App", "Google Play Badge"],
    compat: 91,
    online: true,
    avatarColor: "bg-lime-600",
  },
  {
    id: 10,
    name: "Jessica Tanaka",
    uni: "Universitas Padjadjaran",
    prodi: "Administrasi Bisnis",
    skills: ["Financial Modeling", "Business Dev", "Excel", "Pitch Deck"],
    skillCats: ["business"],
    exp: ["Young Entrepreneur Award 2025", "HIPMI Cup — Finalist"],
    prestasi: ["Best Business Plan"],
    compat: 66,
    online: true,
    avatarColor: "bg-amber-500",
  },
  {
    id: 11,
    name: "Kevin Rahmadan",
    uni: "ITS Surabaya",
    prodi: "Teknik Informatika",
    skills: ["Go", "Microservices", "Docker", "Kubernetes"],
    skillCats: ["backend"],
    exp: ["AWS Cloud Hackathon — Juara 2", "ICPC Asia Regional 2024"],
    prestasi: ["Cloud Expert", "DevOps Certified"],
    compat: 80,
    online: false,
    avatarColor: "bg-violet-500",
  },
  {
    id: 12,
    name: "Lina Maharani",
    uni: "Universitas Diponegoro",
    prodi: "Teknik Informatika",
    skills: ["TensorFlow", "Computer Vision", "NLP", "Data Science"],
    skillCats: ["data-science"],
    exp: ["GEMASTIK XVII AI Track — Juara 1", "IEEE Student Paper Award"],
    prestasi: ["AI Champion", "Best Paper"],
    compat: 87,
    online: true,
    avatarColor: "bg-rose-500",
  },

  /* ── Sosial & Community ── */
  {
    id: 13,
    name: "Maya Putri",
    uni: "Universitas Indonesia",
    prodi: "Ilmu Kesejahteraan Sosial",
    skills: ["Community Building", "Advokasi", "NGO Management", "Social Media"],
    skillCats: ["sosial"],
    exp: ["Koordinator Volunteer UNDP 2025", "Hult Prize Sosial — Juara 1 Campus"],
    prestasi: ["Social Leader Award", "Volunteer of the Year"],
    compat: 74,
    online: true,
    avatarColor: "bg-emerald-500",
  },
  {
    id: 14,
    name: "Naufal Hakim",
    uni: "UGM Yogyakarta",
    prodi: "Sosiologi",
    skills: ["Sosial Impact Design", "Facilitation", "Komunitas", "Fieldwork"],
    skillCats: ["sosial"],
    exp: ["Youth Changemaker UNICEF 2025", "Social Entrepreneurship Program"],
    prestasi: ["Best Impact Project", "SDGs Champion"],
    compat: 70,
    online: false,
    avatarColor: "bg-teal-600",
  },
  {
    id: 15,
    name: "Olivia Rahma",
    uni: "UNPAD Bandung",
    prodi: "Hubungan Internasional",
    skills: ["Advokasi Kebijakan", "Networking", "Social Research", "NGO"],
    skillCats: ["sosial"],
    exp: ["MUN Harvard 2025 — Best Delegate", "Internship UNFPA Indonesia"],
    prestasi: ["Best Delegate", "Global Youth Leader"],
    compat: 77,
    online: true,
    avatarColor: "bg-lime-500",
  },

  /* ── Public Speaking & Presentasi ── */
  {
    id: 16,
    name: "Petra Wijaksono",
    uni: "Universitas Airlangga",
    prodi: "Ilmu Komunikasi",
    skills: ["Public Speaking", "MC", "Storytelling", "Presentasi"],
    skillCats: ["public-speaking"],
    exp: ["Juara 1 Lomba Debat Nasional 2025", "TEDx Speaker UI 2024"],
    prestasi: ["Best Speaker", "TEDx Alumni"],
    compat: 81,
    online: true,
    avatarColor: "bg-sky-500",
  },
  {
    id: 17,
    name: "Qila Ramadhani",
    uni: "Universitas Hasanuddin",
    prodi: "Sastra Indonesia",
    skills: ["Pitching", "Debat", "Storytelling", "Copywriting"],
    skillCats: ["public-speaking", "business"],
    exp: ["Juara 2 Debat Parlemen Nasional 2025", "Brand Storytelling Workshop Facilitator"],
    prestasi: ["Best Orator", "Juara Debat Regional"],
    compat: 68,
    online: false,
    avatarColor: "bg-fuchsia-500",
  },
  {
    id: 18,
    name: "Raka Santanu",
    uni: "Universitas Bina Nusantara",
    prodi: "Marketing Communication",
    skills: ["Presentasi Bisnis", "Public Speaking", "Video Pitch", "Persuasion"],
    skillCats: ["public-speaking", "business"],
    exp: ["Startup Pitch Competition — Juara 1", "Marketing Hackathon 2025 Finalist"],
    prestasi: ["Best Pitch", "Top Presenter"],
    compat: 73,
    online: true,
    avatarColor: "bg-orange-600",
  },

  /* ── Sains & Riset ── */
  {
    id: 19,
    name: "Sinta Larasati",
    uni: "IPB University",
    prodi: "Biokimia",
    skills: ["Lab Research", "Biologi Molekuler", "Academic Writing", "SPSS"],
    skillCats: ["sains-riset"],
    exp: ["LKTIN ITS 2025 — Juara 2", "Riset BRIN Bidang Biokimia"],
    prestasi: ["Best Research Paper", "Young Scientist Award"],
    compat: 65,
    online: false,
    avatarColor: "bg-green-700",
  },
  {
    id: 20,
    name: "Taufik Hidayat",
    uni: "ITB Bandung",
    prodi: "Kimia",
    skills: ["Kimia Analitik", "Lab Work", "Data Sains Eksperimen", "Scientific Writing"],
    skillCats: ["sains-riset"],
    exp: ["Juara 1 Olimpiade Kimia Nasional 2025", "Publikasi Jurnal Scopus 2024"],
    prestasi: ["Olimpiade Gold", "Scopus Author"],
    compat: 62,
    online: true,
    avatarColor: "bg-cyan-700",
  },
  {
    id: 21,
    name: "Ulfah Mardiyah",
    uni: "Universitas Diponegoro",
    prodi: "Fisika",
    skills: ["Fisika Komputasi", "Python", "Simulasi Numerik", "Academic Writing"],
    skillCats: ["sains-riset", "data-science"],
    exp: ["Physics Olympiad Nasional — Juara 3", "IEEE Student Branch Project"],
    prestasi: ["Physics Award", "IEEE Member"],
    compat: 71,
    online: false,
    avatarColor: "bg-blue-700",
  },
];


/* ── Current user profile ── */
const currentUser = {
  name: "Rizki Aditya",
  initials: "RA",
  prodi: "Teknik Informatika",
  uni: "Universitas Indonesia",
  bio: "Mahasiswa Teknik Informatika UI semester 6. Passionate di web development & AI. Suka ikut hackathon dan kompetisi startup. Mencari tim untuk Gemastik & ASEAN Business Plan.",
  stats: { lombaIkuti: 7, timAktif: 3, undangan: 2, matchRate: "92%" },
  skills: [
    { label: "React.js",       cls: "tag-purple" },
    { label: "Node.js",        cls: "tag-purple" },
    { label: "UI/UX",          cls: "tag-orange" },
    { label: "Python",         cls: "tag-blue"   },
    { label: "Machine Learning", cls: "tag-green" },
    { label: "TypeScript",     cls: "tag-purple" },
    { label: "Figma",          cls: "tag-pink"   },
  ],
  riwayat: [
    {
      emoji: "🏆", bg: "bg-primary-light",
      title: "Hackathon Nasional 2025",
      org: "Kemenkominfo · Tim 3 orang",
      badge: "Juara 2", badgeCls: "text-accent bg-accent-light",
    },
    {
      emoji: "🌱", bg: "bg-green-50",
      title: "Hult Prize Campus Round 2025",
      org: "Hult International · Tim 4 orang",
      badge: "Top 10", badgeCls: "text-green-700 bg-green-100",
    },
    {
      emoji: "💡", bg: "bg-blue-50",
      title: "Ksatria Data UI 2024",
      org: "BEM FTUI · Solo",
      badge: "Peserta", badgeCls: "text-blue-700 bg-blue-100",
    },
  ],
  prestasi: [
    { title: "Ksatria Data 2024", sub: "Juara 1 Kategori ML" },
    { title: "Dokumentasi Terbaik", sub: "Gemastik XVI 2024" },
    { title: "Google DSC Speaker", sub: "Web3 Workshop 2025" },
  ],
  deadlines: [
    { id: 1, day: "14", month: "Mei", name: "Gemastik XVII PPL",    left: "2 hari",  urgentCls: "text-red-500",   dotCls: "bg-red-400 pulse",  bgCls: "bg-red-50",   numCls: "text-red-500"  },
    { id: 7, day: "21", month: "Mei", name: "ASEAN Business Plan",  left: "9 hari",  urgentCls: "text-accent",    dotCls: "bg-accent",         bgCls: "bg-accent-light", numCls: "text-accent"  },
    { id: 11, day: "3",  month: "Jun", name: "Hult Prize Campus",    left: "22 hari", urgentCls: "text-primary",   dotCls: "bg-primary",        bgCls: "bg-primary-light", numCls: "text-primary" },
  ],
};
